name: Copy html folder to gh-branch

on:
  push:
    branches:
      - 2023-11-01

jobs:
  copy:
    name: Copy html to gh-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: 'html'
          TARGET_BRANCH: 'gh-pages'
        run: |
          #files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          #git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git checkout 2023-11-01 -- html
          rm -rf 2023-11-01/html
          mv html 2023-11-01 
	  git add -A .
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
