name: Copy html folder to gh-branch

on:
  push:
    branches:
      - 2023-11-01

jobs:
  copy:
    name: Copy html to gh-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy
        env:
          SRC_FOLDER_PATH: 'html'
          TARGET_BRANCH: 'gh-pages'
        run: |
          #git config --global user.name 'GitHub Action'
          #git config --global user.email 'action@github.com'
          git fetch
          git checkout $TARGET_BRANCH
          #git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git checkout 2023-11-01 -- $SRC_FOLDER_PATH
          mkdir -p 2023-11-01
          rm -rf 2023-11-01/$SRC_FOLDER_PATH
          mv $SRC_FOLDER_PATH 2023-11-01 
          git add -A .
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push
